spring:
  flyway:
    enabled: false
app:
  name: code
db:
  common:
    minIdle: 5
    maxPoolSize: 10
    idleTimeout: 10000
    dialect: org.hibernate.dialect.PostgreSQLDialect
  master:
    userName: tmp
  jpa:
    master:
      schema: master
      url: jdbc:postgresql://mugu.synology.me:55432/tmp?characterEncoding=UTF-8&useSSL=false
      ddl-auto: none
      entity-packages: com.egstep.code.entity
  mybatis:
    common:
      driver-class-name: org.postgresql.Driver
      idleTimeout: 10000
    manage:
      url: jdbc:postgresql://mugu.synology.me:55432/tmp?ssl=false&charset=utf8
